// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://domowndymxzudifedbgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbW93bmR5bXh6dWRpZmVkYmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDgzMDgsImV4cCI6MjA3MTI4NDMwOH0.VHASfGb68eZCl6VOTqWWs2d42j30Pc5aHDb8JEDYfx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});